name: my_ci

on:
  push: 
   branches: [ main ]
  pull_request:
   branches: [ main ]
  workflow_dispatch:

jobs:
  # sample_job:
  #  runs-on: ubuntu-latest
  # #  strategy:
  # #    matrix:
  # #     os: [ ubuntu-latest , windows-latest ,macOS-latest ]
  #  steps:
  #    - name: Prints repo details
  #      run: echo "step -repo 1${{ github.ref }} -branch ${{ github.repository }}"
  #    - name: Check out repository code
  #      uses: actions/checkout@v3
  #    - name: job status
  #      run: echo "job status = ${{ job.status }}"  
  # docker_push:
  #    runs-on: ubuntu-latest
  #    steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: build docker image
  #       run: |
  #        docker build -t v1 .
  #        echo "name ${{ secrets.DOCKER_USERNAME }} pw :${{ secrets.DOCKER_TOKEN }} "
  #     - uses: actions/checkout@v1
  #     - name: Login to DockerHub Registry
  #       run: echo  ${{ secrets. }} | docker login -u  ${{ secrets.DOCKER_HUB_USERNAME}} --password-stdin
  #     - name: push to docker hub
  #       run: |
  #        docker push keyzersoze/ci_learn:v1
  login:
    runs-on: ubuntu-latest
    steps:
      -        
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
   
  