name: my_ci

on:
  push: 
   branches: [ main ]
  pull_request:
   branches: [ main ]
  workflow_dispatch:

jobs:
  my_Job:
   runs-on: ubuntu-latest
   steps:
     - run: echo "step -repo 1${{ github.ref }} -branch ${{ github.repository }}"
     - name: Prints name
       run: echo "kayzersozzzzzzzze"
     - name: Check out repository code
       uses: actions/checkout@v3
     - name: job status
       run: echo "job status = ${{ job.status }}"  