name: my_ci

on:
  push: 
   branches: [ main ]
  pull_request:
   branches: [ main ]
  workflow_dispatch:

jobs:
  sample_job:
   runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #     os: [ ubuntu-latest , windows-latest ,macOS-latest ]
   steps:
     - name: Prints repo details
       run: echo "step -repo 1${{ github.ref }} -branch ${{ github.repository }}"
     - name: Check out repository code
       uses: actions/checkout@v3
     - name: job status
       run: echo "job status = ${{ job.status }}"  
  docker_push:
     runs-on: ubuntu-latest
     steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: build docker image
        run: |
         docker version
         pwd 
         ls
         docker build -t v1 .
      - name: push to docker hub
        run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_TOKEN }}
         docker push keyzersoze/ci_learn:v1
